-- Enable pgvector
CREATE EXTENSION IF NOT EXISTS vector;

-- Videos: core content metadata
CREATE TABLE IF NOT EXISTS videos (
    id SERIAL PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,
    source TEXT NOT NULL DEFAULT 'youtube',  -- youtube, rss, manual
    title TEXT,
    channel TEXT,
    description TEXT,
    duration_sec INTEGER,
    thumbnail_url TEXT,
    transcript_hash TEXT,  -- SHA256 of transcript for dedup
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ADHD-specific tagging matrix (generated by Claude)
CREATE TABLE IF NOT EXISTS video_tags (
    id SERIAL PRIMARY KEY,
    video_id INTEGER REFERENCES videos(id) ON DELETE CASCADE,
    pacing SMALLINT CHECK (pacing BETWEEN 1 AND 10),          -- cut speed / info density
    stimulation SMALLINT CHECK (stimulation BETWEEN 1 AND 10), -- audio/visual density
    novelty SMALLINT CHECK (novelty BETWEEN 1 AND 10),         -- how unique/obscure
    vibe TEXT,                                                  -- "late-night-rabbit-hole", "high-energy-tutorial"
    mood_tags TEXT[] DEFAULT '{}',                              -- ["focused", "analytical", "tired"]
    content_tags TEXT[] DEFAULT '{}',                           -- ["tech", "science", "ambient"]
    claude_summary TEXT,                                        -- 2-3 sentence summary
    tagged_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(video_id)
);

-- Semantic embeddings for vector search fallback
CREATE TABLE IF NOT EXISTS video_embeddings (
    id SERIAL PRIMARY KEY,
    video_id INTEGER REFERENCES videos(id) ON DELETE CASCADE,
    embedding vector(768),  -- gemini-embedding-001 (output_dimensionality=768)
    model TEXT DEFAULT 'gemini-embedding-001',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(video_id)
);

-- User preferences (persisted across sessions)
CREATE TABLE IF NOT EXISTS user_preferences (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL DEFAULT 'default',
    interest_tags TEXT[] DEFAULT '{}',
    exclude_vibes TEXT[] DEFAULT '{}',
    preferred_pacing_min SMALLINT DEFAULT 3,
    preferred_pacing_max SMALLINT DEFAULT 8,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id)
);

-- Playback log for learning loop
CREATE TABLE IF NOT EXISTS playback_log (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL DEFAULT 'default',
    video_id INTEGER REFERENCES videos(id),
    watch_duration_sec INTEGER,
    skipped BOOLEAN DEFAULT FALSE,
    skip_reason TEXT,
    mood_tags_at_play TEXT[] DEFAULT '{}',
    played_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_video_tags_mood ON video_tags USING GIN(mood_tags);
CREATE INDEX IF NOT EXISTS idx_video_tags_pacing ON video_tags(pacing);
CREATE INDEX IF NOT EXISTS idx_video_tags_vibe ON video_tags(vibe);
CREATE INDEX IF NOT EXISTS idx_video_embeddings_vec ON video_embeddings USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_playback_log_user ON playback_log(user_id, played_at DESC);

-- ============================================================
-- Music tables (Migration 002) — ADDITIVE, video tables above
-- are untouched.
-- ============================================================

-- Tracks: core audio content metadata (parallel to videos)
CREATE TABLE IF NOT EXISTS tracks (
    id SERIAL PRIMARY KEY,
    url TEXT,
    source VARCHAR(20) NOT NULL DEFAULT 'upload' CHECK (source IN ('upload', 'jamendo', 'openverse', 'incompetech', 'ccmixter')),
    source_id VARCHAR(100),
    title VARCHAR(500) NOT NULL,
    artist VARCHAR(300),
    album VARCHAR(300),
    duration_sec INTEGER,
    file_path TEXT,
    hls_path TEXT,
    artwork_path TEXT,
    fingerprint TEXT,
    musicbrainz_id VARCHAR(36),
    file_hash VARCHAR(64),
    status VARCHAR(20) NOT NULL DEFAULT 'processing' CHECK (status IN ('processing', 'ready', 'error')),
    license VARCHAR(50),
    attribution TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tracks_file_hash ON tracks(file_hash) WHERE file_hash IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_tracks_source_id ON tracks(source, source_id) WHERE source_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tracks_source ON tracks(source);
CREATE INDEX IF NOT EXISTS idx_tracks_status ON tracks(status);
CREATE INDEX IF NOT EXISTS idx_tracks_artist ON tracks(artist);

-- Track tags: audio-specific tagging matrix (parallel to video_tags)
CREATE TABLE IF NOT EXISTS track_tags (
    id SERIAL PRIMARY KEY,
    track_id INTEGER NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
    energy INTEGER CHECK (energy BETWEEN 1 AND 10),
    bpm INTEGER,
    musical_key VARCHAR(10),
    danceability INTEGER CHECK (danceability BETWEEN 1 AND 10),
    acousticness INTEGER CHECK (acousticness BETWEEN 1 AND 10),
    vibe VARCHAR(100),
    mood_tags TEXT[] DEFAULT '{}',
    genre_tags TEXT[] DEFAULT '{}',
    claude_summary TEXT,
    tagged_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(track_id)
);

CREATE INDEX IF NOT EXISTS idx_track_tags_mood ON track_tags USING GIN(mood_tags);
CREATE INDEX IF NOT EXISTS idx_track_tags_genre ON track_tags USING GIN(genre_tags);
CREATE INDEX IF NOT EXISTS idx_track_tags_energy ON track_tags(energy);
CREATE INDEX IF NOT EXISTS idx_track_tags_vibe ON track_tags(vibe);

-- Media embeddings: unified vector store for both videos and tracks
CREATE TABLE IF NOT EXISTS media_embeddings (
    id SERIAL PRIMARY KEY,
    media_type VARCHAR(10) NOT NULL CHECK (media_type IN ('video', 'track')),
    video_id INTEGER REFERENCES videos(id) ON DELETE CASCADE,
    track_id INTEGER REFERENCES tracks(id) ON DELETE CASCADE,
    embedding vector(768),
    model VARCHAR(100) DEFAULT 'gemini-embedding-001',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CHECK (
        (media_type = 'video' AND video_id IS NOT NULL AND track_id IS NULL) OR
        (media_type = 'track' AND track_id IS NOT NULL AND video_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_media_embeddings_track ON media_embeddings USING hnsw (embedding vector_cosine_ops) WHERE media_type = 'track';
CREATE INDEX IF NOT EXISTS idx_media_embeddings_video ON media_embeddings USING hnsw (embedding vector_cosine_ops) WHERE media_type = 'video';

-- Playlists
CREATE TABLE IF NOT EXISTS playlists (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL DEFAULT 'default',
    name VARCHAR(300) NOT NULL,
    description TEXT,
    auto_generated BOOLEAN DEFAULT FALSE,
    mood_tags TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_playlists_user ON playlists(user_id);

-- Playlist tracks (ordered join table)
CREATE TABLE IF NOT EXISTS playlist_tracks (
    id SERIAL PRIMARY KEY,
    playlist_id INTEGER NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
    track_id INTEGER NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    added_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(playlist_id, position)
);

-- Extend playback_log for music (additive columns only)
ALTER TABLE playback_log ADD COLUMN IF NOT EXISTS content_type VARCHAR(10) DEFAULT 'video';
ALTER TABLE playback_log ADD COLUMN IF NOT EXISTS track_id INTEGER REFERENCES tracks(id);

-- Extend user_preferences for music (additive columns only)
ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS preferred_genres TEXT[] DEFAULT '{}';
ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS audio_quality VARCHAR(10) DEFAULT '128k';

-- ============================================================
-- Remediation indexes and constraints (Migration 003)
-- ============================================================

-- UNIQUE constraints on media_embeddings to prevent duplicate embeddings
CREATE UNIQUE INDEX IF NOT EXISTS idx_media_embeddings_track_unique
    ON media_embeddings(track_id) WHERE track_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_media_embeddings_video_unique
    ON media_embeddings(video_id) WHERE video_id IS NOT NULL;

-- Fingerprint UNIQUE index for cross-source dedup
CREATE UNIQUE INDEX IF NOT EXISTS idx_tracks_fingerprint_unique
    ON tracks(fingerprint) WHERE fingerprint IS NOT NULL;

-- Trigram indexes for ILIKE search performance
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_tracks_title_trgm ON tracks USING GIN (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_tracks_artist_trgm ON tracks USING GIN (artist gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_tracks_album_trgm ON tracks USING GIN (album gin_trgm_ops);

-- Composite indexes for playback_log music queries
CREATE INDEX IF NOT EXISTS idx_playback_log_music
    ON playback_log(user_id, content_type, played_at DESC)
    WHERE content_type = 'track';
CREATE INDEX IF NOT EXISTS idx_playback_log_music_skip
    ON playback_log(user_id, content_type, skipped, played_at DESC)
    WHERE content_type = 'track' AND skipped = TRUE;

-- Composite index for tracks status+created_at (library default sort)
CREATE INDEX IF NOT EXISTS idx_tracks_status_created
    ON tracks(status, created_at DESC) WHERE status = 'ready';

-- Fingerprint index for pipeline dedup queries
CREATE INDEX IF NOT EXISTS idx_tracks_fingerprint
    ON tracks(fingerprint) WHERE fingerprint IS NOT NULL;

-- Constraint: ready tracks must have hls_path
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_ready_has_hls') THEN
        ALTER TABLE tracks ADD CONSTRAINT chk_ready_has_hls
            CHECK (status != 'ready' OR hls_path IS NOT NULL);
    END IF;
END$$;

-- Constraint: source_id must not be empty string (normalize to NULL)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_source_id_not_empty') THEN
        ALTER TABLE tracks ADD CONSTRAINT chk_source_id_not_empty
            CHECK (source_id IS NULL OR length(source_id) > 0);
    END IF;
END$$;

-- ============================================================
-- PANNs audio embeddings (Migration 007) — Sprint 11 S11.3
-- ADDITIVE ONLY — existing vector(768) column is untouched.
-- ============================================================

-- Track which dimension an embedding was generated at.
-- Existing rows default to 768 (Gemini).
ALTER TABLE media_embeddings ADD COLUMN IF NOT EXISTS embedding_dim INTEGER DEFAULT 768;

-- Separate column for PANNs CNN14 audio embeddings (2048-dim).
-- Kept separate from the text-based 768-dim column so that:
--   1. Existing Gemini embedding queries are unaffected.
--   2. We can index and query audio vs. text embeddings independently.
--   3. pgvector HNSW indexes cannot be shared across different dimensions.
ALTER TABLE media_embeddings ADD COLUMN IF NOT EXISTS audio_embedding vector(2048);

-- NOTE: pgvector HNSW indexes are limited to 2000 dimensions.
-- PANNs embeddings are 2048-dim, so we skip the HNSW index.
-- Brute-force cosine search (<=> operator) is fast for <10K tracks.
-- If the catalog grows past 10K, consider PCA to 2000-dim or IVFFlat.

-- ============================================================
-- Beat detection data (Migration 004) — ADDITIVE
-- ============================================================

-- Store librosa beat analysis results alongside existing track tags.
-- JSONB structure: { beat_times: float[], downbeat_times: float[],
--                    tempo: float, beat_strength: float[] }
ALTER TABLE track_tags ADD COLUMN IF NOT EXISTS beat_data JSONB;

-- ============================================================
-- Waveform visualization data (Migration 005) — ADDITIVE
-- ============================================================

-- Pre-computed amplitude envelope for the waveform visualiser.
-- Stored as a JSONB array of 0.0-1.0 floats (typically 800 points).
-- NULL means the waveform has not been generated yet; the frontend
-- falls back to the flat progress bar in that case.
ALTER TABLE track_tags ADD COLUMN IF NOT EXISTS waveform_data JSONB;

-- ============================================================
-- Song structure analysis (Migration 006) — Sprint 11 Audio Intelligence
-- ============================================================

-- Self-similarity segmentation results stored per track.
-- JSONB structure: list of {label, start_sec, end_sec, confidence} objects.
-- label is one of: intro, verse, chorus, bridge, drop, outro,
--                  instrumental, breakdown
-- NULL means structure analysis has not been run yet.
ALTER TABLE track_tags ADD COLUMN IF NOT EXISTS structure JSONB;

-- ============================================================
-- Tag source tracking (Migration 008) — Sprint 11 S11.5
-- ADDITIVE ONLY — existing rows default to 'gemini'.
-- ============================================================

-- Records which pipeline produced the tags for a given track.
-- Values: 'gemini' (Gemini Flash, legacy) | 'local' (local ML pipeline, S11.4+)
-- Used by batch_retag.py to skip already-locally-tagged tracks.
ALTER TABLE track_tags ADD COLUMN IF NOT EXISTS tag_source VARCHAR(20) DEFAULT 'gemini';

-- Index for efficient skip-detection queries in batch_retag
CREATE INDEX IF NOT EXISTS idx_track_tags_source ON track_tags(tag_source);

-- ============================================================
-- Camelot harmonic mixing (Migration 009) — Sprint 11 S11.6
-- ADDITIVE ONLY — all columns above are untouched.
-- ============================================================

-- Camelot wheel code for the track (e.g. "8B", "12A").
-- Populated by the audio analyzer alongside musical_key.
-- VARCHAR(3) covers the full wheel: "1A"-"12B".
ALTER TABLE track_tags ADD COLUMN IF NOT EXISTS camelot_code VARCHAR(3);

-- Index for harmonic-preference ORDER BY (CASE WHEN camelot_code = ANY(...))
-- and for any future explicit WHERE filters on compatible keys.
CREATE INDEX IF NOT EXISTS idx_track_tags_camelot ON track_tags(camelot_code);
